"use client";

import { useEffect, useState } from 'react';
import { useSupabase, useUser } from '../../components/SupabaseProvider';
import type { RecipeResult, WeeklyPlan } from '../../lib/llmTypes';
import { preferencesFromPersonalization } from '../../lib/personalization';
import type { PersonalizationAnswers } from '../../lib/personalization';
import Modal from '../../components/Modal';

/**
 * Weekly plan page.  Allows the user to generate a full seven‑day meal
 * plan based on their fridge contents and preferences. The plan is
 * generated by the LLM via a retrieval‑augmented prompt. This page
 * mirrors the Genius page but produces multiple meals instead of a
 * single recipe.
 */
export default function WeeklyPlanPage() {
  const { supabase } = useSupabase();
  const user = useUser();
  const [fridgeItems, setFridgeItems] = useState<any[]>([]);
  const [measurementTypes, setMeasurementTypes] = useState<any[]>([]);
  const [mealTypes, setMealTypes] = useState<any[]>([]);
  // suggestMode indicates whether the user wants to allow additional
  // ingredients for the next plan generation. After a plan is
  // generated, its suggest status is stored in the plan itself so
  // toggling this state does not affect the current plan display.
  const [suggestMode, setSuggestMode] = useState<boolean>(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  // plan holds the current weekly plan along with an extra
  // property `suggest` indicating whether it was generated in
  // suggest mode. We treat this as `any` so we can attach
  // additional fields without TypeScript complaints.
  const [plan, setPlan] = useState<any | null>(null);
  // Aggregated missing items for all meals (used in the modal)
  const [allMissing, setAllMissing] = useState<{ name: string; quantity: number; unit: string }[]>([]);
  const [showMissingModal, setShowMissingModal] = useState(false);

  // When aggregated items are displayed in the modal, they are stored
  // in this state so that the user can edit quantities or remove
  // items. We clone allMissing into this state when the modal opens.
  const [editMissingItems, setEditMissingItems] = useState<{
    name: string;
    quantity: number;
    unit: string;
  }[]>([]);

  // When a plan is loaded from the database, each meal may have an
  // optional recipeId associated with it. We use this to store and
  // update feedback. The type system doesn’t know about this field
  // but we attach it dynamically.

  // Load fridge items, measurement types and meal types on mount
  useEffect(() => {
    if (!user) return;
    const load = async () => {
      const { data: items } = await supabase
        .from('fridge_items')
        .select('*')
        .eq('user_id', user.id);
      setFridgeItems(items || []);
      const { data: mt } = await supabase.from('measurement_types').select('*');
      setMeasurementTypes(mt || []);
      const { data: mTypes } = await supabase.from('meal_types').select('*');
      setMealTypes(mTypes || []);

      // Try to load the most recent weekly plan from the database. A
      // plan is considered valid if it was created within the last
      // seven days. We fetch the latest plan for the user and check
      // its week_start_date. If valid, we set it as the current plan.
      const { data: plans } = await supabase
        .from('meal_plans')
        .select('id, week_start_date, plan, created_at')
        .eq('user_id', user.id)
        .order('created_at', { ascending: false })
        .limit(1);
      if (plans && plans.length > 0) {
        const latest = plans[0] as any;
        const startDate = new Date(latest.week_start_date);
        const now = new Date();
        const diffDays = (now.getTime() - startDate.getTime()) / (1000 * 60 * 60 * 24);
        if (diffDays < 7) {
          // Attach the suggest flag from the stored plan if present. If
          // absent, assume false. When saving a plan we store
          // { week: [...], suggest: boolean }.
          const storedPlan = latest.plan as any;
          setPlan({ ...storedPlan });
        }
      }
    };
    load();
  }, [supabase, user]);

  async function handleGenerate() {
    if (!user) return;
    if (fridgeItems.length === 0) {
      setError('Your fridge is empty. Add some items first.');
      return;
    }
    setLoading(true);
    setError(null);
    try {
      // Build fridge payload similar to Genius page for weekly plan
      const fridgePayload = fridgeItems.map((item) => {
        const measurementName =
          measurementTypes.find((m) => m.id === item.measurement_type_id)?.name || '';
        return {
          name: item.name,
          quantity: item.quantity,
          unit: measurementName,
          expires: item.expiration_date
        };
      });
      // Prefer user_personalization (quiz) for preferences; fall back to profiles + user_allergens + user_preferences
      let prefsObj: { diet?: string; allergens: string[]; likes: string[]; dislikes: string[] };
      let personalization: PersonalizationAnswers | null = null;
      const { data: personalizationRow } = await supabase
        .from('user_personalization')
        .select('answers')
        .eq('user_id', user.id)
        .maybeSingle();
      if (personalizationRow?.answers && typeof personalizationRow.answers === 'object') {
        personalization = personalizationRow.answers as PersonalizationAnswers;
        prefsObj = preferencesFromPersonalization(personalization);
      } else {
        const { data: profileData } = await supabase
          .from('profiles')
          .select('diet_type_id')
          .eq('user_id', user.id)
          .maybeSingle();
        const profile = profileData as { diet_type_id?: number } | null;
        let dietName: string | undefined;
        if (profile?.diet_type_id) {
          const { data: dietType } = await supabase
            .from('diet_types')
            .select('name')
            .eq('id', profile.diet_type_id)
            .single();
          dietName = (dietType as any)?.name;
        }
        const { data: allergenRows } = await supabase
          .from('user_allergens')
          .select('name')
          .eq('user_id', user.id);
        const allergens = allergenRows
          ? (allergenRows as { name: string }[]).map((row) => row.name)
          : [];
        const { data: prefRows } = await supabase
          .from('user_preferences')
          .select('name, preference_type')
          .eq('user_id', user.id);
        const prefs = prefRows as { name: string; preference_type: string }[] | null;
        let likes: string[] = [];
        let dislikes: string[] = [];
        if (prefs) {
          prefs.forEach((p) => {
            if (p.preference_type === 'like') likes.push(p.name);
            else dislikes.push(p.name);
          });
        }
        prefsObj = { diet: dietName, allergens, likes, dislikes };
      }
      const weeklyRes = await fetch('/api/generate-weekly', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          fridge: fridgePayload,
          preferences: prefsObj,
          suggestMode,
          personalization
        })
      });
      const weeklyData = await weeklyRes.json();
      if (!weeklyRes.ok) {
        throw new Error(weeklyData.error || 'Failed to generate weekly plan');
      }
      const result = weeklyData.plan as WeeklyPlan;
      // For each meal in the weekly plan, insert a recipe row so
      // that feedback can be saved. We also attach the inserted
      // recipe ID to the meal.  Meals may be named differently to
      // the values in the meal_types table, so we perform a
      // case-insensitive match to find the appropriate ID.  When
      // suggestMode is true, we allow missing ingredients but we
      // compute missing items here for later use.
      const insertedPlan: any = { week: [], suggest: suggestMode };
      for (const dayPlan of result.week) {
        const newMeals: any[] = [];
        for (const meal of dayPlan.meals) {
          // Determine meal_type_id
          const mType = mealTypes.find(
            (m) => m.name.toLowerCase() === meal.mealType.toLowerCase()
          );
          let mealTypeId: number | null = null;
          if (mType) mealTypeId = mType.id;
          // Insert recipe into DB or reuse existing if same title
          let newId: number | null = null;
          let existingInfo: any = null;
          if (user) {
            // Check for existing recipe with same title for this user
            const { data: existingRec } = await supabase
              .from('recipes')
              .select('id, created_at, meal_type_id, rating, feedback')
              .eq('user_id', user.id)
              .ilike('title', meal.title)
              .maybeSingle();
            if (existingRec && 'id' in existingRec) {
              newId = (existingRec as any).id;
              existingInfo = existingRec;
            } else {
              // Use the diet type classified by the same LLM that generated this meal.
              const knownDiets = ['vegan', 'vegetarian', 'pescatarian', 'omnivore'];
              const dietNameRaw =
                meal.dietType && typeof meal.dietType === 'string'
                  ? meal.dietType.trim().toLowerCase()
                  : '';
              const validDietName = knownDiets.includes(dietNameRaw) ? dietNameRaw : null;
              let dietId: number | null = null;
              if (validDietName) {
                const { data: dtRow } = await supabase
                  .from('diet_types')
                  .select('id')
                  .eq('name', validDietName)
                  .maybeSingle();
                if (dtRow && 'id' in dtRow) {
                  dietId = (dtRow as any).id;
                }
              }
              const { data: inserted, error: insErr } = await supabase
                .from('recipes')
                .insert({
                  user_id: user.id,
                  title: meal.title,
                  meal_type_id: mealTypeId,
                  ingredients: meal.ingredients,
                  steps: meal.steps,
                  diet_type_id: dietId
                })
                .select('id, created_at, meal_type_id, rating, feedback');
              if (!insErr && inserted && inserted.length > 0) {
                newId = inserted[0].id as number;
                existingInfo = inserted[0];
              }
            }
          }
          // Compute missing ingredients if suggestMode using
          // normalised names to handle partial matches and
          // singular/plural variations.
          let missingItems: { name: string; quantity: number; unit: string }[] = [];
          if (suggestMode) {
            // Build tokens for fridge items with normalisation and synonyms
            const normalizeBase = (str: string) => {
              const lower = str.toLowerCase().trim();
              // Remove non letters and split into words
              const words = lower.replace(/[^a-z\s]/g, '').split(/\s+/).filter(Boolean);
              let last = words[words.length - 1] || lower;
              // Convert plural forms to singular when simple (remove trailing s/es)
              if (last.endsWith('es') && last.length > 3) {
                last = last.slice(0, -2);
              } else if (last.endsWith('s') && last.length > 3) {
                last = last.slice(0, -1);
              }
              // Synonyms mapping for variant normalisation
              const synonyms: Record<string, string> = {
                toast: 'bread',
                sliced: 'bread',
                baguette: 'bread',
                roll: 'bread',
                loaf: 'bread',
                arborio: 'rice',
                jasmine: 'rice',
                basmati: 'rice',
                brown: 'rice'
              };
              const base = synonyms[last] || last;
              return base;
            };
            const fridgeTokens = fridgeItems.map((i) => {
              const full = i.name.toLowerCase().trim();
              const base = normalizeBase(i.name);
              return { full, base };
            });
            meal.ingredients.forEach((ing: any) => {
              const ingFull = ing.name.toLowerCase().trim();
              const ingBase = normalizeBase(ing.name);
              let found = false;
              for (const f of fridgeTokens) {
                if (
                  f.full === ingFull ||
                  f.base === ingBase ||
                  f.full.includes(ingBase) ||
                  ingBase.includes(f.base)
                ) {
                  found = true;
                  break;
                }
              }
              if (!found) {
                const parts = ing.quantity.trim().split(/\s+/);
                let qty = 1;
                let unit = '';
                if (parts.length >= 2) {
                  const maybeNum = parseFloat(parts[0]);
                  if (!Number.isNaN(maybeNum)) {
                    qty = maybeNum;
                    unit = parts[1].toLowerCase();
                  }
                }
                missingItems.push({ name: ing.name, quantity: qty, unit });
              }
            });
          }
          newMeals.push({ ...meal, id: newId, missing: missingItems, existingInfo });
        }
        insertedPlan.week.push({ day: dayPlan.day, meals: newMeals });
      }
      setPlan(insertedPlan);
      // Persist the weekly plan to the database. Compute the week start
      // date as the Monday of the current week.  If a plan for the
      // same user and week already exists, we simply insert a new one
      // and rely on selecting the most recent when loading.  The plan
      // JSON includes the recipe IDs and missing items.
      const now = new Date();
      const dayOfWeek = now.getDay();
      const monday = new Date(now);
      const diffToMonday = (dayOfWeek + 6) % 7; // convert Sunday=0 to 6
      monday.setDate(now.getDate() - diffToMonday);
      const weekStartDate = monday.toISOString().split('T')[0];
      await supabase.from('meal_plans').insert({
        user_id: user.id,
        week_start_date: weekStartDate,
        plan: insertedPlan
      });
    } catch (err: any) {
      setError(err.message || 'Failed to generate weekly plan');
    }
    setLoading(false);
  }

  // Add all missing items from the weekly plan to the shopping list. We
  // aggregate quantities of the same item/measurement before
  // inserting/updating. Only available when suggestMode is enabled and
  // there are missing ingredients.
  async function handleAddAllMissing() {
    if (!user || !plan) return;
    // Aggregate missing items across all meals
    const aggregate: Record<string, { name: string; quantity: number; unit: string }> = {};
    for (const day of plan.week) {
      for (const meal of (day as any).meals) {
        if (meal.missing) {
          (meal.missing as any[]).forEach((m: any) => {
            const key = `${m.name.toLowerCase()}|${m.unit}`;
            if (!aggregate[key]) {
              aggregate[key] = { name: m.name, quantity: 0, unit: m.unit };
            }
            aggregate[key].quantity += m.quantity;
          });
        }
      }
    }
    // Populate modal state and show modal. Convert map to array.
    const items = Object.values(aggregate);
    if (items.length === 0) return;
    setAllMissing(items);
    setEditMissingItems(items.map((i) => ({ ...i })));
    setShowMissingModal(true);
  }

  // Add missing ingredients from a single meal to the shopping list
  async function handleAddMealMissing(dayIndex: number, mealIndex: number) {
    if (!user || !plan) return;
    const meal = (plan.week[dayIndex] as any).meals[mealIndex];
    if (!meal || !meal.missing || (meal.missing as any[]).length === 0) return;
    const missingList: any[] = meal.missing as any[];
    const { data: mtData } = await supabase.from('measurement_types').select('*');
    const mtList = mtData || [];
    for (const m of missingList) {
      const mt = mtList.find((t) => t.name.toLowerCase() === m.unit);
      const fallback = mtList.find((t) => t.name.toLowerCase() === 'pieces');
      const mtId = mt ? mt.id : fallback?.id;
      if (!mtId) continue;
      const { data: existing } = await supabase
        .from('shopping_list')
        .select('id, quantity')
        .eq('user_id', user.id)
        .eq('name', m.name)
        .eq('measurement_type_id', mtId)
        .maybeSingle();
      if (existing && 'id' in existing) {
        await supabase
          .from('shopping_list')
          .update({ quantity: (existing as any).quantity + m.quantity })
          .eq('id', (existing as any).id);
      } else {
        await supabase.from('shopping_list').insert({
          user_id: user.id,
          name: m.name,
          quantity: m.quantity,
          measurement_type_id: mtId
        });
      }
    }
    // Mark meal as added to prevent re-adding
    setPlan((prev: any) => {
      if (!prev) return prev;
      const updated = JSON.parse(JSON.stringify(prev)) as any;
      updated.week[dayIndex].meals[mealIndex].addedToShopping = true;
      return updated;
    });
  }

  // Regenerate a single meal within the weekly plan.  This calls
  // generateRecipe with the meal type specified and updates the
  // existing plan in state and database.  Missing ingredients are
  // recomputed if suggestMode is active.
  async function handleRegenerateMeal(dayIndex: number, mealIndex: number) {
    if (!user || !plan) return;
    const dayPlan = plan.week[dayIndex];
    const meal = (dayPlan as any).meals[mealIndex];
    // Build fridge payload
    const fridgePayload = fridgeItems.map((item) => {
      const measurementName = measurementTypes.find((m) => m.id === item.measurement_type_id)?.name || '';
      return {
        name: item.name,
        quantity: item.quantity,
        unit: measurementName,
        expires: item.expiration_date
      };
    });
    // Prefer user_personalization for preferences; fall back to profiles + user_allergens + user_preferences
    let prefsObj: { diet?: string; allergens: string[]; likes: string[]; dislikes: string[] };
    let personalization: PersonalizationAnswers | null = null;
    const { data: personalizationRow } = await supabase
      .from('user_personalization')
      .select('answers')
      .eq('user_id', user.id)
      .maybeSingle();
    if (personalizationRow?.answers && typeof personalizationRow.answers === 'object') {
      personalization = personalizationRow.answers as PersonalizationAnswers;
      prefsObj = preferencesFromPersonalization(personalization);
    } else {
      const { data: profileData } = await supabase
        .from('profiles')
        .select('diet_type_id')
        .eq('user_id', user.id)
        .maybeSingle();
      let dietName: string | undefined;
      if (profileData && profileData.diet_type_id) {
        const { data: dietType } = await supabase
          .from('diet_types')
          .select('name')
          .eq('id', profileData.diet_type_id)
          .single();
        dietName = (dietType as any)?.name;
      }
      const { data: allergenRows } = await supabase
        .from('user_allergens')
        .select('name')
        .eq('user_id', user.id);
      const allergens = allergenRows ? (allergenRows as any[]).map((r) => r.name) : [];
      const { data: prefRows } = await supabase
        .from('user_preferences')
        .select('name, preference_type')
        .eq('user_id', user.id);
      let likes: string[] = [];
      let dislikes: string[] = [];
      if (prefRows) {
        (prefRows as any[]).forEach((p) => {
          if (p.preference_type === 'like') likes.push(p.name);
          else dislikes.push(p.name);
        });
      }
      prefsObj = { diet: dietName, allergens, likes, dislikes };
    }
    const mTypeName = meal.mealType;
    const regenRes = await fetch('/api/generate', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        fridge: fridgePayload,
        preferences: prefsObj,
        options: { mealType: mTypeName, portions: 1, suggestMode },
        personalization
      })
    });
    const regenData = await regenRes.json();
    if (!regenRes.ok) {
      throw new Error(regenData.error || 'Failed to regenerate meal');
    }
    const result = regenData.recipe as RecipeResult;
    // Insert new recipe row or reuse existing; compute missing
    const mTypeRecord = mealTypes.find((m) => m.name.toLowerCase() === mTypeName.toLowerCase());
    let recipeId: number | null = null;
    if (user) {
      // Check for existing recipe with same title for user
      const { data: existingRec } = await supabase
        .from('recipes')
        .select('id')
        .eq('user_id', user.id)
        .ilike('title', result.title)
        .maybeSingle();
      if (existingRec && 'id' in existingRec) {
        recipeId = (existingRec as any).id;
      } else {
        // Use the diet type classified by the same LLM that generated the recipe.
        const knownDiets = ['vegan', 'vegetarian', 'pescatarian', 'omnivore'];
        const dietNameRaw =
          result.dietType && typeof result.dietType === 'string'
            ? result.dietType.trim().toLowerCase()
            : '';
        const validDietName = knownDiets.includes(dietNameRaw) ? dietNameRaw : null;
        let dietId: number | null = null;
        if (validDietName) {
          const { data: dtRow } = await supabase
            .from('diet_types')
            .select('id')
            .eq('name', validDietName)
            .maybeSingle();
          if (dtRow && 'id' in dtRow) dietId = (dtRow as any).id;
        }
        const { data: inserted, error: insErr } = await supabase
          .from('recipes')
          .insert({
            user_id: user.id,
            title: result.title,
            meal_type_id: mTypeRecord ? mTypeRecord.id : null,
            ingredients: result.ingredients,
            steps: result.steps,
            diet_type_id: dietId
          })
          .select('id');
        if (!insErr && inserted && inserted.length > 0) {
          recipeId = inserted[0].id as number;
        }
      }
    }
    // Compute missing for new meal using normalised names
    let missingList: { name: string; quantity: number; unit: string }[] = [];
    if (suggestMode) {
      const normalizeBase = (str: string) => {
        const lower = str.toLowerCase().trim();
        // Remove non letters and split into words
        const words = lower.replace(/[^a-z\s]/g, '').split(/\s+/).filter(Boolean);
        let last = words[words.length - 1] || lower;
        // Convert plural forms to singular when simple (remove trailing s/es)
        if (last.endsWith('es') && last.length > 3) {
          last = last.slice(0, -2);
        } else if (last.endsWith('s') && last.length > 3) {
          last = last.slice(0, -1);
        }
        // Synonyms mapping for variant normalisation
        const synonyms: Record<string, string> = {
          toast: 'bread',
          sliced: 'bread',
          baguette: 'bread',
          roll: 'bread',
          loaf: 'bread',
          arborio: 'rice',
          jasmine: 'rice',
          basmati: 'rice',
          brown: 'rice'
        };
        const base = synonyms[last] || last;
        return base;
      };
      const fridgeTokens = fridgeItems.map((i) => {
        const full = i.name.toLowerCase().trim();
        const base = normalizeBase(i.name);
        return { full, base };
      });
      result.ingredients.forEach((ing) => {
        const ingFull = ing.name.toLowerCase().trim();
        const ingBase = normalizeBase(ing.name);
        let found = false;
        for (const f of fridgeTokens) {
          if (
            f.full === ingFull ||
            f.base === ingBase ||
            f.full.includes(ingBase) ||
            ingBase.includes(f.base)
          ) {
            found = true;
            break;
          }
        }
        if (!found) {
          const parts = ing.quantity.trim().split(/\s+/);
          let qty = 1;
          let unit = '';
          if (parts.length >= 2) {
            const maybeNum = parseFloat(parts[0]);
            if (!Number.isNaN(maybeNum)) {
              qty = maybeNum;
              unit = parts[1].toLowerCase();
            }
          }
          missingList.push({ name: ing.name, quantity: qty, unit });
        }
      });
    }
    // Update state plan and capture updatedPlan for DB update
    let updatedPlan: any;
    setPlan((prev: any) => {
      if (!prev) return prev;
      const copy = JSON.parse(JSON.stringify(prev)) as any;
      copy.week[dayIndex].meals[mealIndex] = {
        mealType: mTypeName,
        title: result.title,
        ingredients: result.ingredients,
        steps: result.steps,
        id: recipeId,
        missing: missingList,
        rating: null,
        feedback: null
      };
      updatedPlan = copy;
      return copy;
    });
    // Update DB: update existing plan row instead of inserting new
    const now = new Date();
    const dayOfWeek = now.getDay();
    const monday = new Date(now);
    const diffToMonday = (dayOfWeek + 6) % 7;
    monday.setDate(now.getDate() - diffToMonday);
    const weekStartDate = monday.toISOString().split('T')[0];
    // Use upsert to ensure single row per week_start_date and user
    await supabase
      .from('meal_plans')
      .update({ plan: updatedPlan, created_at: new Date().toISOString() })
      .eq('user_id', user.id)
      .eq('week_start_date', weekStartDate);
  }

  // Confirm adding all missing items to the shopping list.  Iterates
  // over the editable list and updates/inserts each item.  After
  // completion, closes the modal and resets state.
  async function confirmAddAllMissing() {
    if (!user || editMissingItems.length === 0) {
      setShowMissingModal(false);
      return;
    }
    // Fetch measurement types once
    const { data: mtData } = await supabase.from('measurement_types').select('*');
    const mtList = mtData || [];
    for (const itm of editMissingItems) {
      const mt = mtList.find((m) => m.name.toLowerCase() === itm.unit);
      const fallback = mtList.find((m) => m.name.toLowerCase() === 'pieces');
      const mtId = mt ? mt.id : fallback?.id;
      if (!mtId) continue;
      const { data: existing } = await supabase
        .from('shopping_list')
        .select('id, quantity')
        .eq('user_id', user.id)
        .eq('name', itm.name)
        .eq('measurement_type_id', mtId)
        .maybeSingle();
      if (existing && 'id' in existing) {
        await supabase
          .from('shopping_list')
          .update({ quantity: (existing as any).quantity + itm.quantity })
          .eq('id', (existing as any).id);
      } else {
        await supabase.from('shopping_list').insert({
          user_id: user.id,
          name: itm.name,
          quantity: itm.quantity,
          measurement_type_id: mtId
        });
      }
    }
    // After adding all items, mark each meal as addedToShopping to disable individual buttons
    setPlan((prev: any) => {
      if (!prev) return prev;
      const copy = JSON.parse(JSON.stringify(prev)) as any;
      for (const day of copy.week) {
        for (const meal of day.meals) {
          if (meal.missing && (meal.missing as any[]).length > 0) {
            meal.addedToShopping = true;
          }
        }
      }
      return copy;
    });
    // Success message and close modal
    setError('Missing ingredients added to shopping list');
    setShowMissingModal(false);
  }

  function cancelAddAllMissing() {
    setShowMissingModal(false);
  }

  return (
    <div className="app-page">
      {!user ? (
        <p className="page-lead">
          Please <a href="/login">log in</a> to generate a weekly plan.
        </p>
      ) : (
        <>
          <h1 className="page-title">Weekly plan</h1>
          <p className="page-lead">Plan your week and keep shopping in sync with your fridge.</p>
          {error && <p className="app-message app-message--error">{error}</p>}
          <div className="app-section app-section--medium app-section--mb">
            <label className="app-checkbox-row">
              <input
                type="checkbox"
                checked={suggestMode}
                onChange={(e) => {
                  setSuggestMode(e.target.checked);
                }}
                disabled={loading}
              />
              <span>
                Suggest recipes with missing ingredients (enables shopping list)
              </span>
            </label>
            <div className="app-card-actions mt-4">
            <button
              onClick={handleGenerate}
              disabled={loading || fridgeItems.length === 0}
              className="btn"
            >
              {loading ? 'Generating…' : plan ? 'Regenerate Weekly Plan' : 'Generate Weekly Plan'}
            </button>
            {plan && plan.suggest && (() => {
              // Compute if there are any missing items across the plan
              let missingCount = 0;
              for (const day of plan.week) {
                for (const meal of (day as any).meals) {
                  if (meal.missing && (meal.missing as any[]).length > 0) {
                    missingCount += (meal.missing as any[]).length;
                  }
                }
              }
              return missingCount > 0 ? (
                <button
                  onClick={handleAddAllMissing}
                  className="btn btn-ghost"
                >
                  Add All Missing Ingredients
                </button>
              ) : null;
            })()}
            </div>
          </div>
          {plan && (
            <div className="app-day-grid">
              {plan.week.map((dayPlan: any, dayIdx: number) => (
                <div
                  key={dayIdx}
                  className="app-card app-card--day"
                >
                  <h2 className="app-detail-title app-detail-title--sm">
                    {(dayPlan as any).day}
                  </h2>
                  {(dayPlan as any).meals.map((meal: any, mealIdx: number) => (
                    <div
                      key={mealIdx}
                      className={`app-recipe-card${
                        plan?.suggest && meal.missing?.length ? ' app-recipe-card--missing' : ''
                      }`}
                    >
                      <h3 className="app-detail-subtitle app-detail-subtitle--flush">
                        {meal.mealType}: {meal.title}
                      </h3>
                      <ul className="app-ingredient-list">
                        {meal.ingredients.map((ing: any, idx: number) => {
                          // Highlight missing only if the plan was generated in suggest mode
                          const highlightMissing = plan && plan.suggest;
                          const isMissing = highlightMissing && meal.missing && (meal.missing as any[]).some((m) => m.name.toLowerCase() === ing.name.toLowerCase());
                          return (
                            <li key={idx} className={isMissing ? 'text-danger' : undefined}>
                              {ing.quantity} {ing.name}
                            </li>
                          );
                        })}
                      </ul>
                      <ol className="app-step-list">
                        {meal.steps.map((step: string, idx: number) => (
                          <li key={idx}>{step}</li>
                        ))}
                      </ol>
                      {/* If this recipe existed previously, show info */}
                      {meal.existingInfo && (
                        <div className="app-recipe-meta">
                          You already used this recipe on{' '}
                          {new Date(meal.existingInfo.created_at).toLocaleDateString()} for{' '}
                          {mealTypes.find((t) => t.id === meal.existingInfo.meal_type_id)?.name || 'this meal'}.{' '}
                          {meal.existingInfo.rating
                            ? `You rated it ${meal.existingInfo.rating}⭐.`
                            : 'You have not rated it yet.'}
                          {meal.existingInfo.feedback
                            ? ` Comment: ${meal.existingInfo.feedback}`
                            : ''}
                        </div>
                      )}
                      {plan && plan.suggest && meal.missing && (meal.missing as any[]).length > 0 && (
                        <div className="app-subsection">
                          <h4 className="app-subsection-title">Missing</h4>
                          <ul className="app-ingredient-list mb-2">
                            {(meal.missing as any[]).map((m: any, idx: number) => (
                              <li key={idx}>
                                {m.quantity} {m.unit} {m.name}
                              </li>
                            ))}
                          </ul>
                          <button
                            className="btn btn-sm"
                            onClick={() => {
                              // Add this meal's missing items to shopping list
                              handleAddMealMissing(dayIdx, mealIdx);
                            }}
                            disabled={meal.addedToShopping}
                          >
                            {meal.addedToShopping ? 'Added' : 'Add to Shopping'}
                          </button>
                        </div>
                      )}
                      <div className="app-subsection">
                        <button
                          className="btn btn-sm"
                          onClick={() => handleRegenerateMeal(dayIdx, mealIdx)}
                        >
                          Regenerate
                        </button>
                        {meal.id && (
                          <div className="app-feedback">
                            <div className="app-feedback-row mt-2">
                              <label className="app-label">Rating</label>
                              <select
                                value={meal.rating ?? ''}
                                onChange={(e) => {
                                  const value = e.target.value;
                                  setPlan((prev: any) => {
                                    if (!prev) return prev;
                                    const updated = JSON.parse(JSON.stringify(prev)) as any;
                                    updated.week[dayIdx].meals[mealIdx].rating = value ? parseInt(value) : null;
                                    return updated;
                                  });
                                }}
                              >
                                <option value="">--</option>
                                {[1, 2, 3, 4, 5].map((n) => (
                                  <option key={n} value={n}>
                                    {n}⭐
                                  </option>
                                ))}
                              </select>
                              <button
                                className="btn btn-sm"
                                onClick={async () => {
                                  // Save feedback for this meal
                                  const ratingVal = meal.rating || null;
                                  const feedbackVal = meal.feedback || null;
                                  const { error: updErr } = await supabase
                                    .from('recipes')
                                    .update({ rating: ratingVal, feedback: feedbackVal })
                                    .eq('id', meal.id);
                                  if (updErr) {
                                    setError(updErr.message || 'Failed to save feedback');
                                  } else {
                                    setError('Feedback saved!');
                                  }
                                }}
                              >
                                Save feedback
                              </button>
                            </div>
                            <div className="app-field">
                              <label className="app-label">Comment</label>
                              <textarea
                                value={meal.feedback ?? ''}
                                onChange={(e) => {
                                  const value = e.target.value;
                                  setPlan((prev: any) => {
                                    if (!prev) return prev;
                                    const updated = JSON.parse(JSON.stringify(prev)) as any;
                                    updated.week[dayIdx].meals[mealIdx].feedback = value;
                                    return updated;
                                  });
                                }}
                                rows={3}
                              />
                            </div>
                          </div>
                        )}
                      </div>
                    </div>
                  ))}
                </div>
              ))}
            </div>
          )}
          <Modal
            open={showMissingModal}
            onClose={cancelAddAllMissing}
            title="Add Missing Ingredients"
          >
            <p className="app-modal-intro">
              Review the missing ingredients below. You can adjust quantities or remove items before adding them to your shopping list.
            </p>
            {editMissingItems.length === 0 ? (
              <p className="app-list-empty">No missing ingredients.</p>
            ) : (
              <div className="app-modal-scroll">
                {editMissingItems.map((itm, idx) => (
                  <div key={idx} className="app-modal-item">
                    <span className="app-modal-item-name">{itm.name}</span>
                    <input
                      type="number"
                      min={0}
                      step="0.1"
                      className="app-input-xs"
                      value={itm.quantity}
                      onChange={(e) => {
                        const val = parseFloat(e.target.value);
                        setEditMissingItems((prev) => {
                          const copy = [...prev];
                          copy[idx] = { ...copy[idx], quantity: isNaN(val) ? 0 : val };
                          return copy;
                        });
                      }}
                    />
                    <span className="text-muted text-sm">{itm.unit}</span>
                    <button
                      type="button"
                      className="btn btn-icon-remove"
                      onClick={() => {
                        setEditMissingItems((prev) => prev.filter((_, i) => i !== idx));
                      }}
                      aria-label={`Remove ${itm.name}`}
                    >
                      ×
                    </button>
                  </div>
                ))}
              </div>
            )}
            <div className="app-actions-row">
              <button type="button" className="btn btn-ghost" onClick={cancelAddAllMissing}>
                Cancel
              </button>
              <button type="button" className="btn" onClick={confirmAddAllMissing} disabled={editMissingItems.length === 0}>
                Add to Shopping List
              </button>
            </div>
          </Modal>
        </>
      )}
    </div>
  );
}